---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      containers:
        - name: api-gateway
      imagePullSecrets:
        - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-greeter
spec:
  template:
    spec:
      containers:
        - name: svc-greeter
      imagePullSecrets:
        - name: regcred
