---
apiVersion: v1
kind: Service
metadata:
  name: public-api-gateway
  annotations:
    service.beta.kubernetes.io/hatoba-load-balancer-name: apigatewaylb
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - name: public
      port: 80
      targetPort: 8080
      nodePort: 32080
  loadBalancerSourceRanges:
    # jp-east-2: https://pfs.nifcloud.com/pdf/ip_ranges.json
    - "157.112.112.0/22"
    - "116.118.224.0/21"
    - "103.233.199.128/26"
    - "157.112.99.0/24"
    - "27.133.232.0/21"
    - "27.133.228.0/24"
