---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "gateway"
        dapr.io/app-protocol: "http"
        dapr.io/app-port: "8080"
        dapr.io/log-as-json: "true"
        dapr.io/log-level: "error"
        dapr.io/config: "common-dapr-config"
    spec:
      containers:
        - name: gateway
          image: kzmake/gateway:latest
          command:
            - /app
          envFrom:
            - configMapRef:
                name: common-config
            - configMapRef:
                name: gateway-config
              prefix: GATEWAY_
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 32Mi
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            tcpSocket: { port: 8080 }
            initialDelaySeconds: 10
          readinessProbe:
            tcpSocket: { port: 8080 }
            initialDelaySeconds: 5
            failureThreshold: 1
            periodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  ADDRESS: 0.0.0.0:8080
  DAPR_ADDRESS: localhost:50001
