FROM python:3.9-slim

RUN pip install poetry

ENV PYTHONUNBUFFERED 1

ENV PYTHONPATH /gen/py
COPY gen/py /gen/py

WORKDIR /app

COPY pyproject.toml .
COPY poetry.lock .
RUN poetry config virtualenvs.create false && poetry install --no-root --no-dev

ARG SERVICE_NAME=svc/echo
COPY microservices/$SERVICE_NAME /app

CMD [ "python", "/app/run.py" ]
