---
apiVersion: skaffold/v2beta19
kind: Config
metadata:
requires:
  - configs: ["app"]
---
apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: app
build:
  artifacts:
    - image: kzmake/api-gateway
      docker: { dockerfile: Dockerfile.golang, buildArgs: { SERVICE_NAME: api/gateway } }
    - image: kzmake/svc-greeter
      docker: { dockerfile: Dockerfile.golang, buildArgs: { SERVICE_NAME: svc/greeter } }
deploy:
  kustomize:
    paths:
      - manifests/overlays/localhost
portForward:
  - resourceType: service
    resourceName: api-gateway
    namespace: default
    port: 8080
    localPort: 58080
  - resourceType: service
    resourceName: svc-greeter
    namespace: default
    port: 5050
    localPort: 55050
