---
apiVersion: skaffold/v2beta22
kind: Config
metadata:
requires:
  - configs: ["app"]
---
apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: app
build:
  artifacts:
    - image: ghcr.io/kzmake/skeleton/api-gateway
      docker: { dockerfile: Dockerfile.golang, network: host, buildArgs: { SERVICE_NAME: api/gateway } }
    - image: ghcr.io/kzmake/skeleton/svc-greeter
      docker: { dockerfile: Dockerfile.golang, network: host, buildArgs: { SERVICE_NAME: svc/greeter } }
    - image: ghcr.io/kzmake/skeleton/svc-echo
      docker: { dockerfile: Dockerfile.golang, network: host, buildArgs: { SERVICE_NAME: svc/echo } }
deploy:
  kustomize:
    paths:
      - manifests/overlays/localhost
portForward:
  - resourceType: service
    resourceName: api-gateway
    namespace: default
    port: 8080
    localPort: 58080
  - resourceType: service
    resourceName: api-gateway-dapr
    namespace: default
    port: 50001
    localPort: 50001
profiles:
  - name: localhost
  - name: production
    deploy:
      kustomize:
        paths:
          - manifests/overlays/production
